services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - './seeds:/app/seeds:ro'
    restart: unless-stopped

  frontend:
    build: ./frontend/nova-app
    environment:
      - BACKEND_URL=http://backend:8100
    depends_on:
      - backend
    restart: unless-stopped
